### ISSUE TITLE
Not really an issue. Need your help

### ISSUE THREAD

**Issue by TamirEliasy** [tfae/rr-low-incall-volume-fix#2]
Hi Bro,

Sorry for opening an issue about this, but you are my only hope and I couldn't find any other way to contact you besides opening an issue.

I'm running RR on my device (ZTE Axon 7). I have the exact opposite problem with my device. It is too loud, and causes an echo effect to the other person who talks with me (it is so loud so that the mic catches the voice of the other person and thus he gets the echo effect). Not to mention that every conversation I make with the phone becomes a public one.

Since you are familiar with how to higher the volume - I thought that you might be the one to know lower it too and that it'll be an easy task for you to help me with it.

I already tried researching and asking for help. No one was familiar with this problem.

Would appreciate any of your help,
Tamir

**Comment by ghost** [comment]
Hi.

Why don't you lower the volume with the volume buttons? lol

Anyway, I can try to help you if you send me your /system/etc/mixer_paths_tasha.xml.

**Comment by TamirEliasy** [comment]
Ohhh... Sorry for not mentioning it. I meant that the high volume problem is with the lowest volume of the device when on call, as I would assume that the low-volume-problem occurs with max volume.

My mixer_paths_tasha.xml is attached in here (archived as ZIP, as it appears gitub does not support uploading XML files).

Many many thanks for the quick reply and for trying to help. Really do appreciate it.

[mixer_paths_tasha.zip](https://github.com/tfae/rr-low-incall-volume-fix/files/1995407/mixer_paths_tasha.zip)

**Comment by ghost** [comment]
Hi, try this Magisk Module:

[rr-high-incall-volume-fix-v1.0b.zip](https://github.com/tfae/rr-low-incall-volume-fix/files/1995834/rr-high-incall-volume-fix-v1.0b.zip)

**Comment by TamirEliasy** [comment]
Hi,

Thanks for the effort and hard work.
Sorry for disappearing for a while. I had a replacement phone for few days, and only when I got mine back, I tested the module.

Unfortunately, this module did  not fix the issue. People still reports that they hear an echo sound of themselves, and I still have a high volume during a call.

I now see that I forgot mentioning that I'm using a call recorder. I have a feeling that it might be related to the issue, but this is not a specific app-related thing. I'm currently using an Xposed module to enable the RR (actually CM) native call recorder, but in the past I used various of apps which with all I experienced the high-volume/echo-effect.

Does the above make sense to you? Does it gives you any idea/direction on how to solve this issue?

Thanks again,
Tamir

**Comment by TamirEliasy** [comment]
Hi again,

was wondering if you had a chance seeing my previous message?

Thanks again,
Tamir

**Comment by ghost** [comment]
Hi.
Try to disable the Xposed module and test.
If it doesn't work, remove Xposed completely and test again.

Xposed is well known for causing issues like that.

**Comment by TamirEliasy** [comment]
Hi,

Thanks for the reply.
I tried that, and indeed it solves the issue, but I'm afraid that Xposed is not the culprit in here. I tried with various alternative recording apps, and those that worked had the same affect (some of them caused other issues too, but the Xposed module was the best one which worked flawlessly, without any other issues besides the loud sound that others have suffered from it).

Call recording is a must for my usage and it seems that this feature causing the loud sound.
Any other idea on how it can be fixed.

Meanwhile, I've found a workaround, which is not perfect and ruins the smooth experience from using the device so I hope I'll be able to find a permanent solution that won't need any interfering from my side.
The workaround I've found is to put the call onto speaker and the cancel it. For some reason it fixes the issue and still the call is being recorded. Maybe this info can pin-point you to the configuration needed for the device volume, so that I won't need to apply this 'trick' for each phone call I make.

Thanks again,
Tamir.

**Comment by ghost** [comment]
Hi,

I have no idea why it happens, so I cannot help you with it.
Try to contact the Xposed module developer.

Good luck!

**Comment by TamirEliasy** [comment]
Hi,
Already tried contacting him. He couldn't help either. And as mentioned - this is not something relates to Xposed. It seems more related to call-recording as it happened with non-Xposed apps too.

Thanks anyway for all the effort and for trying to help.
